"""
frontend/components/chart_panel.py

Enterprise Chart Workspace

Author:
Sanket Kabariya
"""

from __future__ import annotations

import json

import plotly.graph_objects as go
import streamlit as st
from state.dashboard_state import DashboardState

class ChartPanel:
    """
    Enterprise Chart Workspace.
    """

    @staticmethod
    def render():

        chart = DashboardState.chart()

        if chart is None:

            st.subheader("📈 Business Visualization")

            st.info(
                "No visualization available for this analysis."
            )

            return

        try:

            figure = go.Figure(chart)

            st.subheader("📈 Business Visualization")

            # ======================================
            # Toolbar
            # ======================================

            chart_type = (
                figure.data[0].type.title()
                if figure.data
                else "Unknown"
            )

            col1, col2, col3 = st.columns(3)

            with col1:

                st.success(
                    f"📊 {chart_type} Chart"
                )

            with col2:

                st.info("🎨 Plotly")

            with col3:

                chart_json = json.dumps(
                    chart,
                    indent=2,
                )

                st.download_button(

                    "⬇ Download Chart JSON",

                    chart_json,

                    file_name="chart.json",

                    mime="application/json",

                    width="stretch",

                )

            st.divider()

            # ======================================
            # Plotly Chart
            # ======================================

            st.plotly_chart(

                figure,

                width="stretch",

                config={

                    "displayModeBar": True,

                    "displaylogo": False,

                    "responsive": True,

                    "scrollZoom": True,

                    "toImageButtonOptions": {
                        "filename": "business_chart"
                    },

                },

            )

            st.divider()

            # ======================================
            # Chart Information
            # ======================================

            st.caption(
                f"""
Chart Type : {chart_type}

Visualization Engine : Plotly

Generated by AI Business Intelligence Platform
"""
            )

        except Exception as error:

            st.error(
                f"Unable to render chart.\n\n{error}"
            )