"""
frontend/components/chart_panel.py

Interactive Chart Panel.

Displays Plotly charts generated by the
AI Visualization Engine.

Author:
Sanket Kabariya
"""

from __future__ import annotations

import plotly.graph_objects as go
import streamlit as st


class ChartPanel:
    """
    Interactive Chart Component.
    """

    def render(self) -> None:
        """
        Render Plotly chart.
        """

        if "analysis" not in st.session_state:
            return

        response = st.session_state["analysis"]

        chart = response.get("chart")

        if chart is None:

            st.divider()

            st.subheader("📊 Interactive Visualization")

            st.info(
                "No visualization available for this query."
            )

            return

        try:

            figure = go.Figure(chart)

            st.divider()

            st.subheader("📊 Interactive Visualization")

            st.plotly_chart(
                figure,
                width="stretch",
                config={
                    "displayModeBar": True,
                    "responsive": True,
                    "scrollZoom": True,
                },
            )

        except Exception as error:

            st.error(
                f"Unable to display chart.\n\n{error}"
            )