import json

import plotly.io as pio
import streamlit as st


class ChartView:
    """
    Displays the interactive Plotly chart generated by the AI.
    """

    @staticmethod
    def render():

        chart = st.session_state.get("chart")

        if not chart:
            return

        st.subheader("📊 Interactive Visualization")

        try:

            # Support both:
            # chart = {"plotly_json": {...}}
            # chart = {...}
            plotly_json = chart.get("plotly_json", chart)

            # If JSON is returned as a string
            if isinstance(plotly_json, str):
                plotly_json = json.loads(plotly_json)

            figure = pio.from_json(json.dumps(plotly_json))

            st.plotly_chart(
                figure,
                width="stretch",
                theme="streamlit",
            )

        except Exception as e:

            st.warning("Unable to display the generated chart.")

            with st.expander("Error Details"):

                st.code(str(e))