"""
frontend/components/explanation_panel.py

AI Executive Report Panel.

Displays the executive business explanation
generated by the AI.

Author:
Sanket Kabariya
"""

from __future__ import annotations

import streamlit as st


class ExplanationPanel:
    """
    AI Executive Report Component.
    """

    def render(self) -> None:
        """
        Render AI explanation.
        """

        if "analysis" not in st.session_state:
            return

        response = st.session_state["analysis"]

        explanation = response.get("explanation")

        if not explanation:
            return

        st.divider()

        st.subheader("🤖 AI Executive Report")

        if explanation.get("error"):

            st.warning(
                "AI explanation is unavailable.\n\n"
                f"Reason: {explanation['error']}"
            )

            return

        # ----------------------------------------------------
        # Overview
        # ----------------------------------------------------

        if explanation.get("overview"):

            st.markdown("### 📌 Executive Overview")

            st.info(
                explanation["overview"]
            )

        # ----------------------------------------------------
        # Trends
        # ----------------------------------------------------

        if explanation.get("trends"):

            st.markdown("### 📈 Trends")

            st.success(
                explanation["trends"]
            )

        # ----------------------------------------------------
        # Risks
        # ----------------------------------------------------

        if explanation.get("risks"):

            st.markdown("### ⚠️ Risks")

            st.error(
                explanation["risks"]
            )

        # ----------------------------------------------------
        # Opportunities
        # ----------------------------------------------------

        if explanation.get("opportunities"):

            st.markdown("### 🚀 Opportunities")

            st.info(
                explanation["opportunities"]
            )

        # ----------------------------------------------------
        # Recommendations
        # ----------------------------------------------------

        if explanation.get("recommendations"):

            st.markdown("### 💡 Recommendations")

            st.success(
                explanation["recommendations"]
            )

        # ----------------------------------------------------
        # Conclusion
        # ----------------------------------------------------

        if explanation.get("conclusion"):

            st.markdown("### ✅ Conclusion")

            st.write(
                explanation["conclusion"]
            )

        # ----------------------------------------------------
        # Footer
        # ----------------------------------------------------

        if explanation.get("model"):

            st.caption(
                f"Generated by {explanation['model']}"
            )