import streamlit as st


class ReportView:
    """
    Displays the executive report generated by the AI.
    """

    SECTION_CONFIG = [
        ("📌 Executive Overview", "overview"),
        ("📈 Trend Analysis", "trends"),
        ("⚠️ Risk Analysis", "risks"),
        ("💡 Opportunities", "opportunities"),
        ("✅ Recommendations", "recommendations"),
        ("🎯 Final Conclusion", "conclusion"),
    ]

    @staticmethod
    def render():

        report = st.session_state.get("report", {})

        if not report:
            return

        st.subheader("📑 Executive Report")

        for title, key in ReportView.SECTION_CONFIG:

            content = report.get(key)

            if not content:
                continue

            with st.container(border=True):

                st.markdown(f"### {title}")

                st.markdown(content)