"""
frontend/components/sql_panel.py

Generated SQL Viewer.

Displays the SQL generated by the AI.

Author:
Sanket Kabariya
"""

from __future__ import annotations

import streamlit as st


class SQLPanel:
    """
    SQL Display Component.
    """

    def render(self) -> None:
        """
        Display generated SQL.
        """

        if "analysis" not in st.session_state:
            return

        response = st.session_state["analysis"]

        sql = response.get("generated_sql")

        if not sql:
            return

        st.divider()

        st.subheader("📝 Generated SQL")

        st.code(
            sql,
            language="sql",
        )

        col1, col2 = st.columns([1, 4])

        with col1:

            st.download_button(
                label="📥 Download SQL",
                data=sql,
                file_name="generated_query.sql",
                mime="text/plain",
                width="stretch",
            )

        with col2:

            st.success("SQL generated successfully.")