import streamlit as st


class SQLViewer:
    """
    Displays the SQL generated by the AI.
    """

    @staticmethod
    def render():

        sql = st.session_state.get("generated_sql", "")

        if not sql:
            return

        st.subheader("📝 Generated SQL")

        with st.expander(
            "View Generated SQL",
            expanded=True,
        ):

            st.code(
                sql,
                language="sql",
            )

            st.caption(
                "The query above was generated automatically by the AI."
            )

            st.download_button(
                label="⬇ Download SQL",
                data=sql,
                file_name="generated_query.sql",
                mime="text/sql",
                width="stretch",
            )