"""
frontend/components/summary_panel.py

Business Summary Panel.

Displays the structured business summary
generated by the AI Insight Engine.

Author:
Sanket Kabariya
"""

from __future__ import annotations

import streamlit as st


class SummaryPanel:
    """
    Business Summary Component.
    """

    def render(self) -> None:
        """
        Render business summary.
        """

        if "analysis" not in st.session_state:
            return

        response = st.session_state["analysis"]

        summary = response.get("summary")

        if not summary:
            return

        st.divider()

        st.subheader("📋 Business Summary")

        # ---------------------------------------------------
        # Executive Summary
        # ---------------------------------------------------

        if summary.get("executive_summary"):

            st.markdown("### 📌 Executive Summary")

            st.info(
                summary["executive_summary"]
            )

        # ---------------------------------------------------
        # Overview
        # ---------------------------------------------------

        if summary.get("overview"):

            st.markdown("### 📈 Overview")

            st.write(
                summary["overview"]
            )

        # ---------------------------------------------------
        # Trend
        # ---------------------------------------------------

        if summary.get("trend_summary"):

            st.markdown("### 📊 Trend Analysis")

            st.success(
                summary["trend_summary"]
            )

        # ---------------------------------------------------
        # Anomaly
        # ---------------------------------------------------

        if summary.get("anomaly_summary"):

            st.markdown("### ⚠️ Anomaly Analysis")

            st.warning(
                summary["anomaly_summary"]
            )

        # ---------------------------------------------------
        # Recommendations
        # ---------------------------------------------------

        recommendations = summary.get(
            "recommendation_summary",
            [],
        )

        if recommendations:

            st.markdown("### 💡 Recommendations")

            for recommendation in recommendations:

                st.markdown(
                    f"- {recommendation}"
                )