"""
backend/dashboard/dashboard_models.py

Enterprise Dashboard Models.

Defines the internal models used by the
AI Dashboard Builder.

Author:
Sanket Kabariya
"""

from __future__ import annotations


from enum import Enum
from typing import Any
from dataclasses import dataclass, field
from backend.agents.agent_manager import AgentResponse


# ==========================================================
# Widget Types
# ==========================================================

class WidgetType(str, Enum):
    """
    Supported dashboard widgets.
    """

    KPI = "kpi"

    CHART = "chart"

    TABLE = "table"

    SUMMARY = "summary"

    TEXT = "text"


# ==========================================================
# Dashboard Widget
# ==========================================================

@dataclass(slots=True)
class DashboardWidget:

    id: str

    title: str

    widget_type: WidgetType

    question: str = ""

    sql: str = ""

    description: str = ""

    width: int = 6

    height: int = 1


# ==========================================================
# Dashboard Plan
# ==========================================================

@dataclass(slots=True)
class DashboardPlan:
    """
    Output generated by the Dashboard Planner.
    """

    title: str

    description: str

    widgets: list[DashboardWidget] = field(
        default_factory=list
    )


# ==========================================================
# Dashboard Widget Result
# ==========================================================

@dataclass(slots=True)
class DashboardWidgetResult:
    """
    Result of executing one widget.
    """

    widget: DashboardWidget

    response: AgentResponse


# ==========================================================
# Dashboard Result
# ==========================================================

@dataclass(slots=True)
class DashboardResult:
    """
    Complete generated dashboard.
    """

    success: bool

    title: str

    description: str

    widgets: list[DashboardWidgetResult] = field(
        default_factory=list
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    error: str | None = None
    
# ==========================================================
# Dashboard Query
# ==========================================================

@dataclass(slots=True)
class DashboardQuery:
    """
    Dashboard query request.
    """

    widget: DashboardWidget

    question: str


# ==========================================================
# Dashboard Query Result
# ==========================================================

@dataclass(slots=True)
class DashboardQueryResult:
    """
    Result of executing one dashboard query.
    """

    title: str

    question: str

    dataframe: Any

    success: bool

    error: str | None = None


# ==========================================================
# Dashboard KPI
# ==========================================================

@dataclass(slots=True)
class DashboardKPI:
    """
    Dashboard KPI.
    """

    title: str

    value: int | float | str

    description: str = ""


# ==========================================================
# Dashboard Chart
# ==========================================================

@dataclass(slots=True)
class DashboardChart:
    """
    Dashboard Chart.
    """

    title: str

    figure: Any

    chart_type: str

    success: bool

    error: str | None = None

# ==========================================================
# Dashboard Table
# ==========================================================

@dataclass(slots=True)
class DashboardTable:
    """
    Dashboard Table.
    """

    title: str

    columns: list[str]

    rows: list[dict[str, Any]]

# ==========================================================
# Dashboard Summary
# ==========================================================

@dataclass(slots=True)
class DashboardSummary:
    """
    AI generated dashboard summary.
    """

    overview: str

    recommendations: list[str] = field(
        default_factory=list
    )

    risks: list[str] = field(
        default_factory=list
    )

    opportunities: list[str] = field(
        default_factory=list
    )


# ==========================================================
# Final Dashboard
# ==========================================================

@dataclass(slots=True)
class Dashboard:
    """
    Complete AI dashboard.
    """

    title: str

    description: str

    kpis: list[DashboardKPI] = field(
        default_factory=list
    )

    charts: list[DashboardChart] = field(
        default_factory=list
    )
    
    tables: list[DashboardTable] = field(
        default_factory=list
    )
    
    summary: DashboardSummary | None = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )