"""
Chart Models

Defines all chart-related models used by the
Visualization Engine.

Project:
AI Data Analyst
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# -----------------------------------------------------
# Supported Chart Types
# -----------------------------------------------------

class ChartType(str, Enum):
    """
    Supported visualization types.
    """

    BAR = "bar"

    LINE = "line"

    SCATTER = "scatter"

    PIE = "pie"

    HISTOGRAM = "histogram"

    BOX = "box"

    AREA = "area"

    HEATMAP = "heatmap"

    TABLE = "table"


# -----------------------------------------------------
# User Request
# -----------------------------------------------------

@dataclass
class ChartRequest:
    """
    Request received by Chart Agent.
    """

    question: str

    dataframe: Any

    preferred_chart: Optional[ChartType] = None


# -----------------------------------------------------
# Chart Configuration
# -----------------------------------------------------

@dataclass
class ChartConfig:
    """
    Chart configuration generated by
    Chart Selector.
    """

    chart_type: ChartType

    x_axis: str

    y_axis: Optional[str] = None

    color: Optional[str] = None

    title: str = ""

    x_label: str = ""

    y_label: str = ""

    group_by: Optional[str] = None

    aggregation: Optional[str] = None

    sort: bool = False

    ascending: bool = False

    limit: Optional[int] = None


# -----------------------------------------------------
# Chart Result
# -----------------------------------------------------

@dataclass
class ChartResult:
    """
    Final chart generation result.
    """

    success: bool

    chart_type: ChartType

    figure: Any

    config: ChartConfig

    warnings: List[str] = field(default_factory=list)

    error: Optional[str] = None


# -----------------------------------------------------
# Metadata
# -----------------------------------------------------

@dataclass
class DatasetMetadata:
    """
    Dataset information used by the
    chart selection engine.
    """

    row_count: int

    column_count: int

    numeric_columns: List[str]

    categorical_columns: List[str]

    datetime_columns: List[str]